name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    branches: [ main ]
    paths:
      - 'python_oqs_implementation/setup.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'python_oqs_implementation/setup.py'

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install pypa/build and Build package
        run: |
          cd python_oqs_implementation
          python3 -m pip install build --user
          python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: python_oqs_implementation/dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/oqs
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
